{% set name = "osrf_pycommon" %}
{% set version = "0.1.10" %}
{% set sha256 = "429708204cc3c9389e90da637fc0ac797bc6653853599f0ac4b59091f41b6cb4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/osrf//{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - trollius  # [py < 34]

test:
  imports:
    - osrf_pycommon

about:
  home: https://github.com/osrf/osrf_pycommon
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Commonly needed Python modules used by Python software developed at OSRF'
  dev_url: https://github.com/osrf/osrf_pycommon

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
