travis:
  secure:
    BINSTAR_TOKEN: HxVuza1RkzB5eQkTJdYfNapI7Zi0djPfwRwURbu0thLX4wfLVqUdxIfR/Qk+rCw8jmzzHeiJHFeQruqRUw28qULOtkJ16e4FaOGnaOclSIKLqEW+SCkwx0OWuJ6SdI6FE3G3fKdHAAIavgmk2PiffVi3iac3jjzcDgpduVGebYOwzsb1bubTYCcSqe1PIoU1s0DyJqL1PIZknnjHevaLbNGMQOmfvRjMmDRd85KmPZsE4nHz6s0a+zY9pYMevFBXXmW9EM56VDz4lDJkWXUePgPWHeK4+/dlTkebJ9x25I41gTJFYD9awHQ+MMYZSbUePY7QZWGjjDBMfZnAOzV6yY3DSWwD1WaO5tr06lkSVYsdad4NxcYZ6/gHexGhsQA23K3ayDzeDpDNb/DvrNg/JrdupLgtgRw2QAbWnAZ2ec7rwXBOiiyz9JqL07uYp85Pe/H8TfPypb6W8+cdkZc/fDxTlBf/V7k6s7CUsV3j1aHnhFATQn59ZVcFZd+lPdQhNKLJSAoM6gzrgs3BlMdGiH+M4JC5Et2hERgTY8ug2qJfAFlct/30sfyJc8M/WM8C5f8tPuj5GPuIn63cD8s7AoZWTCTEEhHol1CdOSIQ9FW7RmyVe3hUJ5RcVOHNzbAfFGEyX0cQGoHm1/g9snHCGJ4o4jxCG/KRElV/RnC8s3o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
